export const bankImages = [
  { src: "/bankAndCTCP/ocb.jpg", alt: "First" },
  { src: "/bankAndCTCP/acb.jpg", alt: "Second" },
  { src: "/bankAndCTCP/logo_shb.jpg", alt: "Third" },
  { src: "/bankAndCTCP/vcbr.jpg", alt: "vcbr" },
  { src: "/bankAndCTCP/mb.jpg", alt: "mb" },
  { src: "/bankAndCTCP/bidv.jpg", alt: "bidv" },
  { src: "/bankAndCTCP/vpbank.jpg", alt: "vpbank" },
  { src: "/bankAndCTCP/pg.jpg", alt: "pg" },
  { src: "/bankAndCTCP/hongleong.jpg", alt: "hongleong" },
  { src: "/bankAndCTCP/vib.jpg", alt: "vib" },
  { src: "/bankAndCTCP/hd.jpg", alt: "hd" },
  { src: "/bankAndCTCP/bangkok.jpg", alt: "bangkok" },
  { src: "/bankAndCTCP/red.jpg", alt: "red" },
  { src: "/bankAndCTCP/vfm.jpg", alt: "vfm" },
  { src: "/bankAndCTCP/hsc.jpg", alt: "hsc" },
];
