export const specialists = [
  {
    link: "http://sbanktraining.com.vn/vi-VN/news/tabs/25/Chuyen-gia-Phap-ly-Teller.aspx",
    name: "Chuyên gia Pháp lý Teller",
  },
  { link: "#", name: "Chuyên gia Pháp lý Tài sản bảo đảm" },
  { link: "#", name: "Chuyên gia Pháp lý Tín dụng" },
  { link: "#", name: "Chuyên gia Pháp lý Tái thẩm định" },
  { link: "#", name: "Chuyên gia Chính sách Tín dụng" },
  { link: "#", name: "Chuyên gia Pháp chế Ngân hàng" },
  { link: "#", name: "Chuyên gia Pháp lý Treasury" },
  { link: "#", name: "Chuyên gia Pháp lý Quản trị Nhân sự" },
  { link: "#", name: "Chuyên gia Pháp lý PR" },
  { link: "#", name: "Bài học nghề nghiệp qua những Đại án ngân hàng" },
  { link: "#", name: "Pháp lý Tín dụng nền tảng" },
  { link: "#", name: "Pháp lý Khách hàng Tín dụng" },
  { link: "#", name: "Giới hạn Pháp lý trong kinh doanh tín dụng" },
  { link: "#", name: "Kỹ năng lập tờ trình tín dụng doanh nghiệp" },
  { link: "#", name: "Kỹ năng đàm phán, soạn thảo Hợp đồng Tín dụng" },
  { link: "#", name: "Pháp luật về Giao dịch bảo đảm căn bản" },
  { link: "#", name: "Kỹ năng đàm phán, soạn thảo Hợp đồng Bảo đảm tiền vay" },
  { link: "#", name: "Pháp lý Bảo đảm bằng Động sản" },
  { link: "#", name: "Pháp lý Bảo đảm bằng Bất động sản" },
  { link: "#", name: "Pháp lý Bảo đảm bằng Giấy tờ có giá" },
  { link: "#", name: "Pháp lý Nghiệp vụ bảo lãnh ngân hàng" },
  { link: "#", name: "Kỹ năng pháp lý Xử lý nợ" },
  { link: "#", name: "Pháp luật về Dịch vụ ngân hàng căn bản" },
  { link: "#", name: "Kỹ năng Giao dịch bảo đảm trong nghiệp vụ nguồn vốn" },
  { link: "#", name: "Kỹ năng Pháp lý cho CEO Ngân hàng" },
  { link: "#", name: "Kỹ năng pháp lý cho Giám đốc chi nhánh ngân hàng" },
  { link: "#", name: "Kỹ năng thư ký, trợ lý HĐQT và Ban Điều hành Ngân hàng" },
  { link: "#", name: "Kỹ năng soạn thảo văn bản định chế ngân hàng" },
];

export const professionalLegals = [
  { link: "#", name: "Pháp luật Kinh doanh chứng khoán" },
  { link: "#", name: "Pháp lý Nghề Môi giới chứng khoán" },
  { link: "#", name: "Pháp lý Giao dịch vốn" },
  { link: "#", name: "Giới hạn pháp lý trong Kinh doanh chứng khoán" },
  { link: "#", name: "Pháp luật Kinh doanh Quỹ Tín dụng" },
  { link: "#", name: "Pháp luật Kinh doanh Công ty Tài chính" },
  { link: "#", name: "Pháp luật Kinh doanh Bất động sản" },
  { link: "#", name: "Pháp lý về Khách hàng, Đối tác trong Kinh doanh" },
  { link: "#", name: "Pháp luật Kinh doanh" },
  { link: "#", name: "Pháp luật Đầu tư" },
  { link: "#", name: "Kỹ năng Pháp lý Quản trị Doanh nghiệp" },
  { link: "#", name: "Kỹ năng Pháp lý Quản trị Lao động" },
  { link: "#", name: "Kỹ năng soạn thảo Nội quy Lao động" },
  { link: "#", name: "Kỹ năng Quản lý Văn thư" },
  { link: "#", name: "Kỹ năng soạn thảo văn bản" },
  { link: "#", name: "Kỹ năng soạn thảo Báo cáo" },
  { link: "#", name: "Kỹ năng pháp lý dành cho Giám đốc Doanh nghiệp" },
  { link: "#", name: "Kỹ năng soạn thảo Quy chế" },
  { link: "#", name: "Kỹ năng soạn thảo Hợp đồng trong kinh doanh" },
  { link: "#", name: "Kỹ năng trợ lý, thư ký cho GĐ Doanh nghiệp" },
  { link: "#", name: "Kỹ năng quan hệ giao dịch với Ngân hàng" },
  { link: "#", name: "Kỹ năng Pháp chế, Kiểm soát tuân thủ" },
  { link: "#", name: "Kỹ năng giải quyết tranh chấp" },
];

export const trainingPrograms = [
  { text: "Ứng phó thay đổi luật doanh nghiệp" },
  { text: "Kỹ năng pháp lý Quản trị lao động" },
  { text: "Kỹ năng soạn thảo nội quy lao động" },
  { text: "Kỹ năng quản lý văn thư" },
  { text: "Kỹ năng soạn thảo văn bản" },
  { text: "Kỹ năng soạn thảo báo cáo" },
  { text: "Kỹ năng soạn thảo, đàm phán Hợp đồng trong kinh doanh" },
];

export const trainingPrograms2 = [
  { text: "Kỹ năng trợ lý, thư ký cho lãnh đạo doanh nghiệp" },
  { text: "Đào tạo Pháp lý về nghiệp vụ ngân hàng" },
  { text: "Kỹ năng Pháp chế, kiểm soát và tuân thủ" },
  { text: "Kỹ năng Giao dịch với ngân hàng" },
  { text: "Kỹ năng giải quyết tranh chấp" },
  { text: "Cơ chế ủy quyền tài chính" },
];
